### ISSUE TITLE
[US-1] Design of forms/screens for capturing information during the sign in process

### ISSUE THREAD

**Issue by Armengedon** [UB-ES-2018/linkedin#2]
12h
test: review in linkedIn that all screens designed have the same information input

**Comment by visheshsahni** [comment]
Hi @Armengedon 

I hope you dont mind me forking the backend part of project for my start up. If there are any passwords/api tokens, please let me know I will delete those files or change to random value.

**Comment by eloipuertas** [comment]
Hi @visheshsahni 

This is a toy project developed by students as an assigment for a software engineering course in Universitat de Barcelona.  So if you want to use it, it should be at your own risk, we are not responsbile for any bug or error in the code.
