### ISSUE TITLE
[US-9.2] ​Fer el update de la bbdd per modificar l’experiència laboral  de ​​l'usuari

### ISSUE THREAD

**Issue by martuu10** [UB-ES-2018/linkedin#79]

**Comment by Blaieet** [comment]
Com a equip vam decidir que per part de frontend només és mostrará, de moment, l'usuari no la podrá modificar. La tasca, per tant, es realitzará en termes de backend, comprovant el seu funcionament amb Postman. En conseqüència, calculo 4-5 hores
